config/routes.rb
Vlm::Application.routes.draw do
  devise_for :users
  get "navigation/index"
  get 'search/' => 'navigation#search'
  get 'about/' => 'navigation#about'
  resources :movies, only: [:index, :show]
  get 'api/search/', to: 'movies#search', as: :api_search
  get 'proxy' => 'proxy#get', :as => 'proxy'
  root 'navigation#index'

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  include Tire::Model::Search
  include Tire::Model::Callbacks
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movie_controller.rb
class MovieController < ApplicationController
  def index
    @movies = Tire.search 'vlm' do
      query { string '*' }
    end
  end

  def show
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Tire.search 'vlm' do
      query do
        string '*'
      end
    end
  end

  def show
    id = params[:id]
    @movie = Tire.search 'vlm' do
      query { string("_id:#{id}") }
    end
    @movie = @movie.results.first
  end

  def search
    query = params[:query]
    @movies = Tire.search 'vlm', :query => { :prefix => { :title => query } }
    render :json => {:hits => @movies.results}
  end

end

app/controllers/navigation_controller.rb
class NavigationController < ApplicationController
  def index
  end

  def about
  end

  def search
  end
end

app/controllers/proxy_controller.rb
class ProxyController < ApplicationController
  def get
    url = URI.parse(params["url"])
    result = Net::HTTP.get_response(url)
    send_data result.body
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movie_helper.rb
module MovieHelper
end

app/helpers/navigation_helper.rb
module NavigationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Viewers Like Me</title>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to(root_path, class: "navbar-brand brand") do %>
            ViewersLike<span class="sexy">Me</span>
          <% end %>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "About", about_path %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <%= render 'devise/menu/login_items' %>
            <%= render 'devise/menu/registration_items' %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">

      <%= yield %>

    </div> <!-- /container -->

  </body>
</html>

app/views/movie/index.html.erb
<h1>Movies</h1>
<% @movies.results.each do |movie| %>
  <h1><%= movie.title %></h1>
<% end %>

app/views/movie/show.html.erb
<h1>Movie#show</h1>
<p>Find me in app/views/movie/show.html.erb</p>

app/views/movies/index.html.erb
<h1>Movies</h1>
<% @movies.results.each do |movie| %>
  <h1><%= link_to movie.title, movie_path(movie.id) %></h1>
<% end %>

app/views/movies/search.html.erb
<h1>Results<h1>
<% @movies.each do |movie| %>
  <h1><%= movie.title %></h1>
<% end %>

app/views/movies/show.html.erb
<h1>Title: <%= @movie.title %>

app/views/navigation/about.html.erb
<h1>About Page</h1>

app/views/navigation/index.html.erb
<center>
<%# image_tag 'vlm_logo.jpg' %>
</center>
<!-- Main component for a primary marketing message or call to action -->
<div class="jumbotron">
  <h1 class="jumbotron-title brand">ViewersLike<span class="sexy">Me</span></h1>
  <p>This example is a quick exercise to illustrate how the default, static and fixed to top navbar work. It includes the responsive CSS and HTML, so it also adapts to your viewport and device.</p>
  <p>To see the difference between static and fixed top navbars, just scroll.</p>
  <p>
  <%= link_to 'Find your Movie', search_path, class: "btn btn-lg btn-danger"  %>
  </p>
</div>

app/views/navigation/search.html.erb
<div class="row">
    <div class="col-lg-12 movie-search">
        <input type="search" class="form-control input-lg query" placeholder="e.g. Shawshank">
    </div>
</div>

<script type="x-template/mustache" id="template-dropdown">
    <div class="row">
        <div class="col-lg-3 col-md-4 col-sm-5">
            <img height="250" width="169" src="/proxy?url={{img}}"
                style="margin: 10px auto; display: block;">
        </div>
        <div class="col-lg-9 col-md-8 col-sm-7">
            <h2>{{title}} ({{year}})</h2>
            <h3>Rating: {{score}}/10</h3>
            <p>{{description}}</p>
        </div>
    </div>
</script>

<script>
    $(function() {
        $('input.query').typeahead({
            name: 'movies',
            valueKey: 'title',
            template: $('#template-dropdown').html(),
            engine: Hogan,
            remote: {
                url: '/api/search?query=%QUERY',
                filter: function(resp) {
                    console.log(resp);
                    return resp.hits;
                }
            }
        });

        $('.tt-hint').addClass('form-control input-lg');
    });
</script>